require:
- rubocop-performance
AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
# Disable due to https://github.com/bbatsov/rubocop/pull/5230
Style/FormatStringToken:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
Naming/FileName:
  Exclude:
  - '**/Gemfile'
  - '**/Rakefile'
Naming/UncommunicativeMethodParamName:
  Enabled: false
# min/max didn't exist in 2.2.10/2.3.7. Remove this once they EOL
Performance/UnneededSort:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
