AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
Style/FrozenStringLiteralComment:
  Enabled: false
Performance/HashEachMethods:
  Enabled: false
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*'
Naming/FileName:
  Exclude:
  - '**/Gemfile'
  - '**/Rakefile'
